// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddField_Article_Type_Date : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddField_Article_Type_Date));
        
        string IMigrationMetadata.Id
        {
            get { return "201912030609384_AddField_Article_Type_Date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
