// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EditField_FileInfo_UID_FileType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditField_FileInfo_UID_FileType));
        
        string IMigrationMetadata.Id
        {
            get { return "201912060237060_EditField_FileInfo_UID_FileType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
